[package]
name = "roulette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shell-escape = "0.1.5"
termcolor = "1.2.0"  # BurntSushi!
